development:
  encoding: utf8
  adapter: mysql
  database: m2mbrain_development
  username: root

test:
  encoding: utf8
  adapter: mysql
  database: m2mbrain_test
  username: root
  encoding: utf8

production:
  encoding: utf8
  adapter: mysql
  database: m2mbrain_development
  username: root
  encoding: utf8

development_m2m:
  adapter: sqlserver
  mode: odbc
  dsn: m2m_dsn
  database: master
  username: sa
  password: TwistedSister